name: Cucumber
description: Cucumber. Simple, Human Collaboration
author: Cucumber Limited
copyright: Cucumber Limited
edit_url: https://github.com/cucumber/website/edit/master/apps/dynamic/views
show_ribbon: false

git_hub:
  token: <%= ENV['GIT_HUB_TOKEN'] %>
  cache_defaults:
    events: []

# Blog
authors:
  aslak:
    display_name: Aslak Hellesøy
    email: aslak@cucumber.io
    gravatar: 0be0e4aa42aacd9a8a95c792de273ca7
  matt:
    display_name: Matt Wynne
    email: matt@cucumber.io
    gravatar: cdf378de2284d8acf137122e541caa28
  julien:
    display_name: Julien Biezemans
    email: julien@cucumber.io
    gravatar: 07193608fb3c70b2a9449d6cafd6d31a
  paul:
    display_name: Paul Rayner
    email: paul@virtual-genius.com
    gravatar: 4ce180eb1538932a4cc5b14c9eb0e83b
  theo:
    display_name: Theo England
    email: theo@cucumber.io
    gravatar: 3c0add79465e37e2d8514628829fb097
  hamish:
    display_name: Hamish Tedeschi
    email: hamish@cucumber.io
    gravatar: 491881c44e5dbb6b9a7594b5b653df49
  dennis:
    display_name: Dennis Günnewig
    email: dev@fedux.org
    gravatar: 9f112ca52563131ea3855a10db79f1b3
  tooky:
    display_name: Steve Tooke
    email: tooky@cucumber.io
    gravatar: cb98700ec5151a02c191a62cb0d17005
  thomas:
    display_name: Thomas Sundberg
    email: thomas@thinkcode.se
    gravatar: fbaa55683cc693c2e95f63431af00ed0
  josh:
    display_name: Josh Chisholm
    email: josh@featurist.co.uk
    gravatar: 18fdf4bb392ea27b457cb8cef10d1813
  seb:
    display_name: Seb Rose
    email: seb@cucumber.io
    gravatar: fc5168c8ba5fd8727cd924df4b376052
  brasmusson:
    display_name: Björn Rasmusson
    email: B.Rasmusson@computer.org
  mpkorstanje:
    display_name: M.P. Korstanje
    email: rien.korstanje@gmail.com
    gravatar: bc7a840257b5609850cabee995c052c3
  sal:
    display_name: Sal Freudenberg
    email: sal@cucumber.io
    gravatar: 1d2149409cfca90886c0dc1765740177
  cyocum:
    display_name: Christopher Yocum
    email: cyocum@gmail.com
  akshita:
    display_name: Akshita
    email: adeora@gmail.com
    gravatar: 227a00873a92f7d4ddd10ecad10ba963
   

versions:
  cucumber_jvm: 2.3.1
  unsupported_jvm_languages: 2.0.1

community:
  max_recent_contributors: 10
