url: http://localhost:4000
name: Cucumber Pro
description: Cucumber Pro. Collaborative Specifications.
author: Cucumber Limited
copyright: Cucumber Limited
markdown: redcarpet
pygments: true
encoding: UTF-8
exclude:
  - assets
  - node_modules
  - bower_components
  - bower.json
  - package.json
  - Makefile
  - README.md

# Custom vars
email_signup: http://localhost:9292/emails
stripe_publishable_key: pk_test_T7q42yPvLMoONCvPdngMOsJr
stripe_charge_url: http://localhost:9292/subscriptions

# Blog
authors:
  aslak:
    display_name: Aslak Helles√∏y
    email: aslak@cucumber.pro
    gravatar: 0be0e4aa42aacd9a8a95c792de273ca7
  matt:
    display_name: Matt Wynne
    email: matt@cucumber.pro
    gravatar: cdf378de2284d8acf137122e541caa28
  julien:
    display_name: Julien Biezemans
    email: julien@cucumber.pro
    gravatar: 07193608fb3c70b2a9449d6cafd6d31a
